### ISSUE TITLE
KeyError in setter for observation_summaries - when it calls assess_process_obs in XMMPointed

### ISSUE THREAD

**Issue by DavidT3** [DavidT3/DAXA#139]
XMM-Newton Pointed - Generating ODF summary files: 100%|█| 424/424 [06:34<00:00,  1.
Traceback (most recent call last):
  File "xmm_process_script.py", line 31, in <module>
    odf_ingest(lovoccs_arch)
  File "/mnt/ufs18/home-218/turne540/code/DAXA/daxa/process/xmm/_common.py", line 389, in wrapper
    obs_archive.observation_summaries = parsed_obs_info
  File "/mnt/ufs18/home-218/turne540/code/DAXA/daxa/archive/base.py", line 490, in observation_summaries
    self._use_this_obs[mn][o_id] = self._missions[mn].assess_process_obs(rel_dat)
  File "/mnt/ufs18/home-218/turne540/code/DAXA/daxa/mission/xmm.py", line 401, in assess_process_obs
    to_return = {inst: {e_id: True for e_id in list(obs_info[inst]['exposures'].keys())} for inst in insts}
  File "/mnt/ufs18/home-218/turne540/code/DAXA/daxa/mission/xmm.py", line 401, in <dictcomp>
    to_return = {inst: {e_id: True for e_id in list(obs_info[inst]['exposures'].keys())} for inst in insts}
KeyError: 'exposures'

Probably happening because I have acquired an observation with no exposures or something? That would be very weird though. Possibly also iterating through the wrong instruments? I specified only PN, MOS1, and MOS2 for this, and may have left R1, R2, and OM still technically 'allowed' by the mission?

**Comment by DavidT3** [comment]
So the first ObsID I managed to grab that caused this problem (using a workaround to get it to run) was 0095011401 - it only has OM data because it was a calibration observation - that means all of the instruments that DAXA was told to process imply aren't active. The 'proper' fix will be to check that at least one of the requested instruments are active before going to the mission obs info checker.

The list of all the observations (in the LoVoCCS lot) for which an error popped up are:
0095011401
0109980501
0095011501
0112951301
0145260301
0159567901
0827031801
0827032001

**Comment by DavidT3** [comment]
The errors are happening for any observation where not all the expected instruments are activated I think.

**Comment by DavidT3** [comment]
I think the change in behaviour I make is going to be in the mission method that checks to see whether things should be used or not - it'll check the 'active' entry, and if it is false it'll make sure to flag that instrument as being unusable without trying to extract sub-exposure information.
